### PR TITLE
Added License section in README.md

### PR DESCRIPTION
**Pull request by MadhuSaini22**
Resolve issue #110

### CODE REVIEW

**Review by codewithvk — APPROVED** [review]
LGTM 🥇  If you wanna work on image tour then can you please make both changes in one PR?

**Comment by MadhuSaini22** [comment]
Yes, sure 😊

Sent from Mail for Windows

**Comment by MadhuSaini22** [comment]
@codewithvk hey!!
 I had made the README for Tour of entire application:)
you can check it out and tell me is it okay or need changes.
[check out here](https://github.com/MadhuSaini22/code-sync/blob/main/assets/Readme.md)

**Review by codewithvk — APPROVED** [review]
Looks good for me 💯 🥇 Merging Your PR to main Branch

**Comment by MadhuSaini22** [comment]
I had just send you a demo link to ask you if it is okay or need changes ,where I had just made changes in my local repo. It was just an demo and you had just merged the previous commits(License) and now you had told me that it looks good so I had created a pull, request you can merge now.

Sent from Mail for Windows

**Comment by codewithvk** [comment]
@MadhuSaini22 It's totally fine! I had change according to requirement :) No worries 👍🏻

**Pull request merged**
